use recipes;

db.dropDatabase();

db.recipes.insertMany([
    {
        "name" : "Balmoral Chicken",
        "ingredients" : [
            { "amount" : 4,
            "ingredient" : "chicken breasts" },
            { "amount" : 130,
            "unit" : "g",
            "ingredient" : "haggis" },
            { "amount" : 4,
            "ingredient" : "rashes of bacon" },
            { "amount" : 30,
            "unit" : "ml",
            "ingredient" : "olive oil" },
            { "amount" : 20,
            "unit" : "g",
            "ingredient" : "butter" },
        ],
        "method" : "1. Preheat oven to 180°C. \n 2. Slice down the side of each chicken breast, making a pocket. \n 3. Slice the haggis into small chunks and squidge (technical term) into the chicken pocket. \n 4. Wrap each breast in a rasher of bacon and secure with a toothpick if necessary. \n 5. Heat the oil and butter in a non-stick frying pan, sear the bacon wrapped around the chicken breasts. Give 2 minutes on each side. \n 6. Place in an oven proof dish and transfer to the oven for 35-40 minutes or until cooked through & piping hot. \n 7. Serve with the peppercorn sauce and a selection of vegetables and/ or mash potato.",
        "image": "https://www.carolinescooking.com/wp-content/uploads/2022/01/haggis-stuffed-chicken-Balmoral-featured-pic-sq.jpg",
        "dietary": "gluten-free",
        "category": "dinner"
    },
    {
        "name" : "Easy butter chicken",

        "ingredients" : [
            { "amount" : 500 ,
              "unit" : "g",
              "ingredient" : "Skinless boneless chicken thighs"
            },
            { "amount" : 1 ,
              "ingredient" : "Lemon"
            },
            { "amount" : 2 ,
              "ingredient" : "Ground cumin"
            },
            { "amount" : 2 ,
              "unit" : "tsp",
              "ingredient" : "Paprika"
            },
            { "amount" : 1.5 ,
              "unit" : "tsp",
              "ingredient" : "Hot chilli powder"
            },
            { "amount" : 200 ,
              "unit" : "g",
              "ingredient" : "Natural yogurt"
            },
            { "amount" : 2 ,
              "unit" : "tbsp",
              "ingredient" : "Vegetable oil"
            },
            { "amount" : 1 ,
              "ingredient" : "Onion"
            },
            { "amount" : 3 ,
              "ingredient" : "Garlic cloves"
            },
            { "amount" : 1 ,
              "ingredient" : "Green chilli"
            },
            { 
              "ingredient" : "Thumb-sized piece"
            },
            { "amount" : 1 ,
              "unit" : "tsp",
              "ingredient" : "Garam masala"
            },
            { "amount" : 2 ,
              "unit" : "tsp",
              "ingredient" : "Ground fenugreek"
            },
            { "amount" : 3 ,
              "unit" : "tbsp",
              "ingredient" : "Tomato purée"
            },
            { "amount" : 300 ,
              "unit" : "ml",
              "ingredient" : "Chicken stock"
            },
            { "amount" : 50 ,
              "unit" : "g",
              "ingredient" : "Flaked almonds"
            }
        ],
        "method" : "STEP 1: In a medium bowl, mix all the marinade ingredients with some seasoning. Chop the chicken into bite-sized pieces and toss with the marinade. Cover and chill in the fridge for 1 hr or overnight. STEP 2: In a large, heavy saucepan, heat the oil. Add the onion, garlic, green chilli, ginger and some seasoning. Fry on a medium heat for 10 mins or until soft. STEP 3: Add the spices with the tomato purée, cook for a further 2 mins until fragrant, then add the stock and marinated chicken. Cook for 15 mins, then add any remaining marinade left in the bowl. Simmer for 5 mins, then sprinkle with the toasted almonds. Serve with rice, naan bread, chutney, coriander and lime wedges, if you like.",
        "image": "https://img.buzzfeed.com/video-api-prod/assets/6e6a56c27c68410991ce7d4e4acc7dee/BFV8692_Easy_Butter_Chicken_Thumb.jpg",
        "dietary": "vegan",
        "category": "dinner"
    },
    {
        "name" : "Thumbprint Cookies",

        "ingredients" : [
            { "amount" : 270,
              "unit" : "g",
              "ingredient" : "plain flour"
            },
            { "amount" : 100,
              "unit" : "g",
              "ingredient" : "sugar"
            },
            { "amount" : 1,
              "ingredient" : "egg"
            },
            { "amount" : 170,
              "unit" : "g",
              "ingredient" : "butter"
            }],
        
        "image": "https://www.livewellbakeoften.com/wp-content/uploads/2019/07/Thumbprint-Cookies-10-5.jpg",
        "dietary": "gluten-free",
        "category": "sweet"
    },
    {
        "name" : "Mushroom soup",
        "ingredients" : [
            { "amount" : 90,
              "unit" : "g",
              "ingredient" : "butter"},
            { "amount" : 2,
              "ingredient" : "onion"},
            { "amount" : 1,
              "ingredient" : "garlic clove"},
            { "amount" : 500,
              "unit" : "g",
              "ingredient" : "mushrooms"},
            { "amount" : 2,
              "unit" : "tbsp",
              "ingredient" : "plain flour"},
            { "amount" : 1,
              "unit" : "l",
              "ingredient" : "hot chicken stock"},
            { "amount" : 1,
              "ingredient" : "bay leaf"},  
            { "amount" : 4,
              "unit" : "tbsp",
              "ingredient" : "single cream"},
            { "amount" : 1,
              "ingredient" : "small flat-leaf parsley"},     
            ],
        "image": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mushroom_soup-9b55c55.jpg",
        "dietary": "dairy-free",
        "category": "lunch"
    },
    {
        "name" : "Beef Burger",
        "ingredients" : [
            { "amount" : 1,
              "unit" : "kg",
              "ingredient" : "beef mince" },
            { "amount" : 1,
              "ingredient" : "onion" },
            { "amount" : 1,
              "ingredient" : "garlic clove" },
            { "amount" : 2,
              "unit" : "tsp",
              "ingredient" : "dijon mustard" },
            { "amount" : 1,
              "unit" : "tbsp",
              "ingredient" : "Worcestershire sauce" },
            { "amount" : 1,
              "ingredient" : "small handful of chopped fresh flatleaf parsley" },
            { "amount" : 1,
              "ingredient" : "large dill pickle, finely chopped" },
            { "amount" : 1,
              "ingredient" : "egg" },
            { "amount" : 8,
              "ingredient" : "rolls" }
            ],
      "method" : "Place all the ingredients for the burgers in a large bowl. Season and mix well. Cover and chill in the fridge for 1 hour. Using wet hands, shape the mixture into 8 burgers. If you want to cook them straight away skip to step 4. If you are freezing them; place flat between sheets of baking paper in a rigid freezerproof container. Freeze for up to 3 months. When ready to use, defrost the burgers completely in the fridge; this will take 3-4 hours. Heat a griddle pan or barbecue to hot. Brush both sides of the burgers with oil and cook for 3-4 minutes each side or until well browned and cooked. Meanwhile, preheat the grill to medium hot. Top each burger with a slice of cheese and grill for 2 minutes until bubbling. Toast the burger buns until lightly golden. Mix the mayonnaise with the mustard and spread over the base of each bun. Add some tomato, lettuce and avocado slices, then the burger, red onion slices and the other half of the bun. Serve with a small bowl of ketchup and fries, if you like.",
      "image" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/09/905610-1-eng-GB_burger-768x960.jpg",
      "category" : "dinner",
      "servings" : 8
    },  

    {
      "name" : "Buffalo Wings with Blue Cheese Sauce",
      "ingredients" : [
          { "amount" : 3,
            "unit" : "tbsp",
            "ingredient" : "plain flour" },
          { "amount" : 2,
            "unit" : "tsp",
            "ingredient" : "garlic powder" },
          { "amount" : 2,
            "unit" : "tsp",
            "ingredient" : "cayenne pepper" },
          { "amount" : 1,
            "unit" : "tsp",
            "ingredient" : "paprika" },
          { "amount" : 1.5,
            "unit" : "kg",
            "ingredient" : "chicken wings" },
          { "amount" : 120,
            "unit" : "ml",
            "ingredient" : "hot sauce" },
          { "amount" : 100,
            "unit" : "ml",
            "ingredient" : "salted butter" },
          { "amount" : 50,
            "unit" : "g",
            "ingredient" : "soft brown sugar" },
          { "amount" : 3,
            "unit" : "tbsp",
            "ingredient" : "runny honey" },
          { "amount" : 1,
            "unit" : "tbsp",
            "ingredient" : "white wine vinegar" },
          { "amount" : 40,
            "unit" : "g",
            "ingredient" : "salted butter" },
          { "amount" : 2,
            "unit" : "tbsp",
            "ingredient" : "plain flour" },
          { "amount" : 150,
            "unit" : "ml",
            "ingredient" : "whole milk" },
          { "amount" : 150,
            "unit" : "g",
            "ingredient" : "blue cheese (eg. stilton)" },
          { "amount" : 100,
            "unit" : "ml",
            "ingredient" : "soured cream" }
          ],
      "method" : "Mix the flour, garlic powder, cayenne pepper, paprika and a large pinch of salt in a large bowl. Add the chicken and toss to coat, then cover and chill for 30 minutes. For the buffalo sauce, mix all the ingredients in a small pan over a medium heat, stirring often, until smooth. Bring to a simmer, then set aside to cool. For the blue cheese sauce, melt the butter in a medium pan, then add the flour and cook, stirring, for 1 minute. Add the milk gradually, stirring, until smooth and thickened. Bring to a simmer, stirring, then remove from the heat and crumble in the cheese. Stir until smooth. Stir in the soured cream, then season to taste and leave to cool. Light the barbecue so the coals are glowing (and not directly underthe food) or the gas is on medium. Cook the wings for 10-15 minutes with the lid closed, turning from time to time. Transfer the wings to a large bowl and toss with the buffalo sauce, then return to the barbecue and cook for 10-15 minutes more, turning and basting with leftover buffalo sauce, until charred and cooked through. Serve the wings hot, with the cheese sauce and an apple and celery salad, if you like.",
      "image" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2021/06/01.Delicious-BBQ-buffalo-wings-960-768x960.jpg",
      "category" : "dinner",
      "servings" : 4,
      "notes" : ""
      },
      
      // {
      // "name" : "Slow Cooker Pulled Pork",
      // "ingredients" : [
      //     { "amount" : 800,
      //       "unit" : "g",
      //       "ingredient" : "pork shoulder" },
      //     { "amount" : 2,
      //       "ingredient" : "red onions" },
      //     { "amount" : 4,
      //       "ingredient" : "garlic cloves" },
      //     { "amount" : 1,
      //       "unit" : "tbsp",
      //       "ingredient" : "ground cumin" },
      //     { "amount" : 1,
      //       "unit" : "tbsp",
      //       "ingredient" : "ground coriander" },
      //     { "amount" : 0.5,
      //       "unit" : "tsp",
      //       "ingredient" : "chilli powder" },
      //     { "amount" : 0.5,
      //       "unit" : "tsp",
      //       "ingredient" : "paprika" },
      //     { "amount" : 0.5,
      //       "unit" : "tsp",
      //       "ingredient" : "ground all spice" },
      //     { "amount" : 2,
      //       "unit" : "tsp",
      //       "ingredient" : "oregano" },
      //     { "amount" : 4,
      //       "unit" : "tbsp",
      //       "ingredient" : "tomato puree" },
      //     { "amount” : 4,
      //       "unit" : "tbsp",
      //       "ingredient" : "red wine vinegar" },
      //     { "amount" : 400,
      //       "unit" : "g",
      //       "ingredient" : "chopped tomatoes" }
      //     ],
      // "method" : "Add all the ingredients (except the coriander, limes and Tabasco), some salt and pepper and 100ml water to your slow cooker and cook on low for 6 hours, or on high for 4 hours. There’s no need to stir the pork while it’s cooking so you can go out and leave it simmering (see Know-how below for how to cook it in a regular oven). Once the cooking time is up, check the seasoning then, using 2 forks, shred the meat to ‘pull’ it. Serve sprinkled with the coriander, with lime wedges for squeezing, hot sauce, if you like, and rice, as a jacket potato topper or in a Tex-Mex pasta bake.",
      // "image" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2021/04/960_SLOW_COOKED_PULLED_PORK_FLATBREAD_GUACAMOLE_SALSA_02-768x960.jpg",
      // "category" : "dinner",
      // "servings" : 8,
      // "notes" : ""
      // },
      
      {
      "name" : "Ultimate Grilled Cheese Sandwich",
      "ingredients" : [
      { "amount" : 2,
        "ingredient" : "crusty white bread slices" },
      { "amount" : 25,
        "unit" : "g",
        "ingredient" : "cheddar" },
      { "amount" : 25,
        "unit" : "g",
        "ingredient" : "gruyere" },
      { "amount" : 25,
        "unit" : "g",
        "ingredient" : "mozzarella" },
      ],
      "method" : "Lightly toast the bread, then cool slightly. Spread butter on both sides of each slice, then divide the cheeses between them. Heat a splash of oil in the pan over a medium heat. Add both slices of bread, cheese-side up, then cover with the lid to help the cheese start to melt. After 2 minutes, remove the lid and continue frying until the underside of the bread is golden and the cheese looks melty. Carefully and quickly sandwich the 2 slices together so all the cheeses are in the middle, then gently press down with a spatula/fish slice and continue cooking until the cheese has melted and the bread is deep golden – it’s best to turn the sandwich every minute or so. Slice, then serve straightaway with gherkins and pickle/chutney.",
      "image" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2020/01/02.Delicious-January-2020-cheese-sandwich-768x960.jpg",
      "category" : "lunch",
      "servings" : 1,
      "notes" : ""
      },
      
      
      
      // {
      // "name" : "Triple Chocolate Cookies",
      // "ingredients" : [
      // { "amount" : 125,
      //   "unit" : "g",
      //   "ingredient" : "salted butter" },
      // { "amount" : 100,
      //   "unit" : "g",
      //   "ingredient" : "golden caste sugar" },
      // { "amount" : 25,
      //   "unit" : "g",
      //   "ingredient" : "dark muscovado sugar" },
      // { "amount" : 1,
      //   "unit" : "tsp",
      //   "ingredient" : "vanilla bean paste" },
      // { "amount" : 1,
      //   "ingredient" : "medium egg" },
      // { "amount" : 2,
      //   "unit" : "tbsp",
      //   "ingredient" : "milk" },
      // { "amount" : 100,
      //   "unit” : "g",
      //   "ingredient" : "plain flour" },
      // { "amount" : 50,
      //   "unit" : "g",
      //   "ingredient" : "cocoa powder" },
      // { "amount" : 75,
      //   "unit" : "g",
      //   "ingredient" : "chocolate chunks" },
      // ],
      // "method" : "Put the butter and both sugars in a large mixing bowl (or in the bowl of a food processor fitted with a paddle beater) and beat until soft, lightly and creamy (about 7-10 minutes). Stir in the vanilla bean paste. Mix the egg and milk together in a jug, then add to the bowl with the butter/sugar and mix until smooth. Add the flour, cocoa and chocolate chunks and beat to form a smooth dough. Heat the oven to 180ºC/160ºC fan/gas 4. Divide the dough into 14 equal amounts, then roll into rough balls (see tip). Space the balls out over the baking sheets, leaving room for them to spread as they bake. Chill the cookie balls for 30 minutes. Bake the cookies for 12-15 minutes, then remove from the oven. Working with one baking sheet at a time, give the baking sheet a short, sharp bang on the work surface (this knocks out any air in the puffed cookies and gives them the desired ripple effect). Repeat with the other baking sheet. Set both sheets on a wire rack to cool for 5 minutes. Lift the baking paper sheets and cookies onto the wire rack until the biscuits are cool enough to eat.",
      // "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2019/09/triple-chocolate-cookies-768x960.jpg",
      // "category" : "sweet",
      // "servings" : 14,
      // "notes" : ""
      // },
      
      {
      "name" : "Eggs Benedict",
      "ingredients" : [
      { "amount" : 8,
        "ingredient" : "bacon slices" },
      { "amount" : 1,
        "unit" : "tbsp",
        "ingredient" : "white wine vinegar" },
      { "amount" : 4,
        "ingredient" : "english muffins" },
      { "amount" : 1,
        "unit" : "tbsp",
        "ingredient" : "chives" },
      { "amount" : 225,
        "unit" : "g",
        "ingredient" : "unsalted butter" },
      { "amount" : 2,
        "ingredient" : "eggs" },
      { "amount" : 1,
        "ingredient" : "juice of half a lemon" },
      { "amount" : 1,
        "ingredient" : "pinch of cayenne pepper" },
      ],
      "method" : "Put the bacon on the grill tray ready for cooking. Half-fill a large pan with water and bring to the boil. Add the vinegar and a pinch of salt. Split the muffins and line a baking tray with kitchen paper. Next, poach the eggs in 2 batches of four. Turn the vinegar water to a very gentle simmer (a few bubbles at the base of the pan, but no more). Break an egg into a teacup, then slide it into the pan. Repeat 3 times, then cook for 3 minutes. Carefully lift out the eggs with a slotted spoon onto the lined baking tray. Repeat with the other 4 eggs. Cover the poached eggs with cling film (or with a large upturned bowl) and set aside. Leave the water on a gentle simmer. For the hollandaise sauce, put the butter in a small pan and leave over a very low heat until melted. Carefully skim off any foam from the surface, then pour the clear melted butter into a small bowl, leaving behind the milky liquid that will have settled on the base of the pan. Discard the milky liquid, wipe the pan clean, then return the clear melted butter to the pan and put over a low heat. Fill a medium pan with about 5cm water and bring to a simmer. Sit a medium heatproof glass bowl over the pan without the base touching the water. Add the egg yolks and 2 tbsp cold water and whisk by hand or with an electric hand mixer until thick and mousse-like - it needs to feel warm when you dip in your little finger. Heat the grill to high. Increase the heat under the pan of clarified butter until it’s gently bubbling and hot. Remove the bowl containing the egg yolks from over the pan and very gradually drizzle in the hot clarified butter, whisking all the time, until the mixture becomes thick and glossy. Whisk in the lemon juice, cayenne pepper and salt to taste. Cover the bowl with cling film, sit it back over the pan of hot water and set aside off the heat. Toast the muffins until golden. Meanwhile, grill the bacon for 1-2 minutes until just cooked through but not crisp. Slide the poached eggs back into the just-simmering water and leave for 30 seconds. Reline the baking tray with kitchen paper, then lift out the eggs onto the tray and leave to drain briefly. Put 2 muffin halves on each of 4 warmed plates, spread with a little butter and top each half with a bacon rasher and a poached egg. Spoon some of the hollandaise sauce over each egg, sprinkle with chives and a little extra cayenne pepper and serve straightaway.",
      "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/09/eggs-benedict-768x960.jpg",
      "category" : "breakfast",
      "servings" : 4,
      "notes" : ""
      },
      
      // {
      // "name" : "Banoffee Pie",
      // "ingredients" : [
      // { "amount" : 175,
      //   "unit" : "g",
      //   "ingredient" : "plain flour" },
      // { "amount": 50,
      //   "unit" : "g",
      //   "ingredient" : "icing sugar" },
      // { "amount" : 205,
      //   "unit" : "g",
      //   "ingredient" : "butter" },
      // { "amount" : 1,
      //   "ingredient" : "egg" },
      // { "amount" : 115,
      //   "unit" : "g",
      //   "ingredient" : "light muscovado sugar" },
      // { "amount" : 397,
      //   "unit" : "g",
      //   "ingredient" : "carnation caramel" },
      // { "amount" : 0.5,
      //   "unit" : "tsp",
      //   "ingredient" : "sea salt" },
      // { "amount" : 300,
      //   "unit" : "ml",
      //   "ingredient" : "double cream" },
      // { "amount" : 1,
      //   "unit" : "tsp",
      //   "ingredient" : "instant coffee powder" },
      // { "amount" : 2,
      //   "unit" : "tsp",
      //   "ingredient" : "caster sugar" },
      // { "amount" : 5,
      //   "ingredient" : "medium ripe bananas" },
      // { "amount" : 30,
      //   "unit" : “g”,
      //   "ingredient" : "dark chocolate" },
      // ],
      // "method" : "Put a baking sheet on the middle shelf of the oven and heat the oven to 200°C/180°C fan/gas 6. For the pastry, sift the flour, icing sugar and a pinch of salt into a food processor. Add the butter and pulse briefly until the mixture resembles fine breadcrumbs. (Alternatively, sift the flour and icing sugar into a large bowl and rub in the butter using your fingertips.) In a small bowl, beat the egg yolk briefly with 2 tbsp cold water. Tip the crumb mixture into a large bowl, add the egg yolk mixture and bring together into a ball. Turn out onto a lightly floured surface and knead briefly until smooth. Shape into a disc, wrap in cling film and chill for 15 minutes. Once chilled, remove the pastry from the fridge, roll out to a circle 30cm wide and about 3mm thick, then use to line the prepared tin. Chill for another 15 minutes. Line the pastry case with foil and a layer of baking beans or uncooked rice and bake for 15-20 minutes until the edge is biscuit-coloured. Carefully remove the foil and beans/rice and bake for 6-8 minutes more or until crisp and golden. Set aside to cool. While the pastry case cools, make the toffee filling. Put the butter and sugar in a medium pan over a medium heat. Whisk continuously as the butter melts and the sugar dissolves until it comes together ina smooth toffee sauce with no trace of melted butter. Stir in the caramel, then bring to the boil and simmer for 3 minutes. Remove from the heat and stir in the sea salt, if using. Pour the filling into the case and chill for at least 1 hour before topping. For the topping, whip together the cream, coffee powder and caster sugar until just forming soft peaks. Thickly slice the bananas and scatter them evenly over the toffee sauce. Spoon over the cream topping, taking it right to the edges and swirling it attractively as you go. Chill for 1 hour. To serve, carefully remove the pie from the tin to a serving plate. Melt the chocolate in bursts in a microwave (or in a small bowl set over a pan of barely simmering water – don’t let the bowl touch the water), then drizzle it over the pie. Serve cut into wedges.",
      // "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/07/941116-1-eng-GB_banoffee-pie-768x960.jpg",
      // "category" : "sweet",
      // "servings" : 12,
      // "notes" : ""
      // },
      
      // {
      // "name" : "Spiced Beef and Chirozo Empanada",
      // "ingredients" : [
      //   { "amount" : 475,
      //     "unit" : "ml",
      //     "ingredient" : "boiling water" },
      //   { "amount" : 115,
      //     "unit" : "g",
      //     "ingredient" : "lard" },
      //   { "amount" : 1.5,
      //     "unit" : "tsp",
      //     "ingredient" : "salt" },
      //   { "amount" : 750,
      //     "unit" : "g",
      //     "ingredient" : "plain flour" },
      //   { "amount" : 600,
      //     "unit" : "g",
      //     "ingredient" : "beef shin" },
      //   { "amount" : 200,
      //     "unit" : "g",
      //     "ingredient" : "chorizo" },
      //   { "amount" : 1,
      //     "ingredient" : "onion" },
      //   { "amount" : 4,
      //     "ingredient" : "garlic cloves" },
      //   { "amount" : 1,
      //     "unit" : "tsp",
      //     "ingredient" : "paprika" },
      //   { "amount" : 1,
      //     "ingredient" : "pinch off cayenne pepper" },
      //   { "amount” : 1,
      //     "unit" : "tbsp",
      //     "ingredient" : "ground cumin" },
      //   { "amount" : 2,
      //     "unit" : "tbsp",
      //     "ingredient" : "tomato puree" },
      //   { "amount" : 2,
      //     "unit" : "tbsp",
      //     "ingredient" : "thyme" },
      //   { "amount" : 1,
      //     "unit" : "tbsp",
      //     "ingredient" : "oregano" },
      //   { "amount" : 1,
      //     "unit" : "l",
      //     "ingredient" : "beef stock" },
      //   { "amount" : 4,
      //     "ingredient" : "spring onions" }
      // ],
      // "method" : "To make the pastry, put the boiling water, lard and salt in a mixing bowl or jug, then stir to melt the lard. Put the flour in another mixing bowl, then gradually stir in the liquid, not too quickly, until it forms a smooth dough. As soon as it's cool enough, work it with your hands - the dough will become too stiff at the end to work with a spoon. Once all the water has been incorporated, tip the dough out onto a work surface and knead for a few minutes until smooth. The aim is to work the pastry to activate the gluten (unlike with shortcrust, which shouldn't be handled too much). When it's soft and pliable, wrap in cling film and chill. To make the filling, heat a glug of oil in a large sauté pan or deep frying pan over a high heat. Toss the beef in the seasoned flour, shaking off the excess, then fry on all sides until browned and slightly caramelised (don’t crowd the pan – cook in batches if necessary). Transfer to a bowl and set aside. Add the chorizo to the pan and fry until it releases its oil and turns crisp, then turn down the heat, remove the chorizo with a slotted spoon and add to the beef bowl. Add the onion and garlic to the pan and cook gently for 5-10 minutes over a low-medium heat, stirring often, until the onion has softened but not coloured. Add the spices and cook for a few minutes, stirring, then add the tomato purée and herbs, and cook for a further few minutes. Return the meat to the pan, pour in enough stock to cover, then bring to a gentle simmer and cook, uncovered, for 2½-3 hours, stirring frequently, until the beef is very tender. If the mixture looks like it's becoming dry at any point, top up with any leftover stock or freshly boiled water. The liquid should reduce and thicken, but don't let it dry out. Once the beef is tender, stir in the spring onions and olives, then cook for another 5 minutes. Remove from the heat and leave to cool completely, then shred the meat. When you're ready to assemble the empanadas, heat the oven to 200°C/180°C fan/gas 6. Roll out the pastry on a lightly floured surface to the thickness of a £1 coin. (You might find the pastry easier to handle if you cut it in half, then roll out the pieces separately.) Cut out about 15 x 12-15cm diameter circles, using a small plate or saucer as a guide, re-rolling the pastry offcuts as necessary. Put around 2 tbsp of filling (which should now be thick – leave behind any runny sauce) into the centre of each circle and brush the edges with water. Fold the pastry in half to enclose the filling and squeeze the edges to close. You can crimp the edges (like a Cornish pasty) to seal or simply press them with a fork. Put the empanadas on baking sheets lined with non-stick baking paper, then brush with melted lard, butter or beef dripping. Bake for 25-30 minutes until the pastry is golden and crisp, then remove and leave to cool a bit before eating.",
      // "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/07/712647-1-eng-GB_beef-empananads-768x960.jpg",
      // "category" : "dinner",
      // "servings" : 4,
      // "notes" : ""
      // },
      
      {
      "name" : "Cheese and Broccoli Bake",
      "ingredients" : [
        { "amount" : 300,
          "unit" : "g",
          "ingredient" : "macaroni" },
        { "amount" : 200,
          "unit" : "g",
          "ingredient" : "tenderstem broccoli" },
        { "amount" : 50,
          "unit" : "ml",
          "ingredient" : "olive oil" },
        { "amount" : 1,
          "ingredient" : "onion" },
        { "amount" : 50,
          "unit" : "g",
          "ingredient" : "plain flour" },
        { "amount" : 550,
          "unit" : "ml",
          "ingredient" : "semi-skimmed milk" },
        { "amount" : 100,
          "unit" : "g",
          "ingredient" : "spinach" },
        { "amount" : 60,
          "unit" : "g",
          "ingredient" : "cheddar" },
        { "amount" : 60,
          "unit" : "g",
          "ingredient" : "gruyere" },
        { "amount" : 40,
          "unit" : "g",
          "ingredient" : "breadcrumbs" }
      ],
      "method" : "Bring a large pan of salted water to the boil over a high heat. Add the macaroni and cook for 8 minutes or until it still has some bite (al dente). For the last 2 minutes add the broccoli, then drain and rinse under cold water to refresh. Cover with damp kitchen paper. Meanwhile in another large deep saucepan, warm the olive oil over a medium heat. Add the onion and gently fry for 10 minutes or until soft. Add the flour, turn up the heat slightly and cook for 2-3 minutes, stirring, until the flour turns a little darker and smells biscuity. Heat the oven to 200°C/ 180°C fan/gas 6. Turn the heat to low, then slowly add the milk, whisking all the time with a balloon whisk. Turn the heat to medium and stir until the mix thickens and boils gently. Add the spinach and half the grated cheeses. Stir until the spinach wilts and the cheese melts. Add the pasta and broccoli, season to taste, then pour into a 1.5 litre ovenproof dish (see make ahead). Mix the rest of the cheese with the breadcrumbs, then use to top the macaroni. Bake for 20-25 minutes until the top is deep golden brown and the sauce is bubbling. Serve with a sharply dressed green salad, if you like.",
      "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/07/612151-1-eng-GB_delicious_midweekbible_nov15_19015_maccheesespinachbroccoli-768x960.jpg",
      "category" : "dinner",
      "servings" : 4,
      "dietary" : "vegetarian",
      "notes" : ""
      },
      
      // {
      // "name" : "Root Vegetable and Lentil Tagine",
      // "ingredients" : [
      //   { "amount" : 1,
      //     "unit" : "tbsp",
      //     "ingredient" : "olive oil" },
      //   { "amount" : 900,
      //     "unit" : "g",
      //     "ingredient" : "mixed root vegetables" },
      //   { "amount" : 3,
      //     "unit" : "tbsp",
      //     "ingredient" : "dried harissa" },
      //   { "amount" : 1,
      //     "ingredient" : "large handful fresh parsley" },
      //   { "amount" : 200,
      //     "unit" : "g",
      //     "ingredient" : "dried green lentils” },
      //   { "amount" : 800,
      //     "unit" : "g",
      //     "ingredient" : "chopped tomatoes" },
      //   { "amount" : 700,
      //     "unit" : "ml",
      //     "ingredient" : "vegetable stock" },
      //   { "amount" : 1,
      //     "ingredient" : "lemon" },
      //   { "amount" : 6,
      //     "ingredient" : "prunes" },
      //   { "amount" : 1,
      //     "ingredient" : "small cauliflower" },
      //   { "amount" : 500,
      //     "unit" : "g",
      //     "ingredient" : "rice" }
      //   ],
      // "method" : "Heat the oil in a large heavy-based flameproof casserole (with a lid) over a medium heat. Add the root veg and fry for 10 minutes, stirring occasionally, until beginning to soften. Stir in the harissa paste, parsley stalks and lentils. Add the tomatoes and stock, then stir in the preserved lemon and prunes. Bring to a simmer, then cover and cook for 20-25 minutes, stirring occasionally, until the lentils are tender. Stir in the cauliflower, then bring back to a simmer. Season, then cook for 3-4 minutes, uncovered, until the cauliflower is starting to become tender. Add the cauliflower leaves, then cook for 2 minutes more. Serve with coconut yogurt and the parsley leaves scattered over the top, with rice or couscous.",
      // "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2019/03/tagine-768x960.jpg",
      // "category" : "dinner",
      // "servings" : 6,
      // "dietary" : "vegan",
      // "notes" : ""
      // },
      
      {
      "name" : "Vegan Pesto Spaghetti",
      "ingredients" : [
        { "amount" : 2,
          "unit" : "tbsp",
          "ingredient" : "olive oil" },
        { "amount" : 1,
          "ingredient" : "small onion" },
        { "amount" : 2,
          "ingredient" : "garlic cloves" },
        { "amount" : 1,
          "ingredient" : "courgette" },
        { "amount" : 400,
          "unit" : "ml",
          "ingredient" : "vegetable stock" },
        { "amount" : 150,
          "unit" : "g",
          "ingredient" : "spaghetti" },
        { "amount" : 50,
          "unit" : "g",
          "ingredient" : "broad beans" },
        { "amount" : 50,
          "unit" : "g",
          "ingredient" : "runner beans" },
        { "amount" : 1,
          "ingredient" : "lemon" },
        { "amount" : 50,
          "unit" : "g",
          "ingredient" : "green olives" },
        { "amount" : 130,
          "unit" : "g",
          "ingredient" : "vegan pesto" },
        ],
      "method" : "Heat 1 tbsp of the oil in a large pan over a medium heat. Add the chopped onion and cook for 5 minutes until softening. Add the garlic and cook for a further minute. Add the remaining 1 tbsp oil to the pan, then stir in the courgette and fry for 5 minutes until the edges are charred and the courgette slices are lightly coloured. Pour in the stock, stirring to combine, then bring to a simmer and add the spaghetti, broad beans, runner beans and lemon wedges. Simmer on a medium-high heat for 10 minutes or until the pasta is tender (al denté). Once the pasta has cooked and the stock has reduced, add the green olives and pesto, tossing everything together gently to combine. Serve with the lemon zest and juice, an extra drizzle of olive oil and, if you like, and basil leaves.",
      "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2021/08/960_ONE_PAN_PESTO_SPAGHETTI_LEMON_COURGETTES-768x960.jpg",
      "category" : "dinner",
      "servings" : 2,
      "dietary" : "vegan",
      "notes" : ""
      },
      
      {
      "name" : "Orzo with Roasted Veg Sauce",
      "ingredients" : [
          { "amount" : 1,
            "ingredient" : "large red onion" },
          { "amount" : 1,
            "ingredient" : "large red pepper" },
          { "amount" : 1,
            "ingredient" : "large yellow pepper" },
          { "amount" : 4,
            "ingredient" : "garlic cloves" },
          { "amount" : 5,
            "ingredient" : "plum tomatoes" },
          { "amount" : 1,
            "unit" : "tbsp",
            "ingredient" : "balsamic vinegar" },
          { "amount" : 100,
            "unit" : "g",
            "ingredient" : "orzo" },
          { "amount" : 200,
            "unit" : "ml",
            "ingredient" : "vegan vegetable stock" },
          { "amount" : 1,
            "ingredient" : "handful of basil leaves" },
          ],
      "method" : "Heat the oven to 180°C fan/gas 6. Put the onion, peppers and garlic in a roasting tin, drizzle with a little olive oil and add a good pinch of salt. Roast for about 20 minutes. Add the tomatoes and balsamic vinegar and stir. Return the vegetables to the oven and roast for a further 25-30 minutes. At this stage there should be a lovely concentrated sauce in the bottom of the roasting tin. Transfer everything to a food processor and whizz. Pour the sauce into a saucepan, add the orzo and simmer gently for about 10 minutes until the sauce has thickened and reduced and the orzo is starting to soften. Add the vegetable stock in small increments – you probably won’t need all of it. What you’re aiming for is a risotto-like texture, where the orzo is cooked al dente and the sauce is thick and rich. Garnish with basil leaves before serving.",
      "images" : "https://www.deliciousmagazine.co.uk/wp-content/uploads/2021/06/960-Orzo-with-roasted-vegetable-sauce-768x960.jpg",
      "category" : "dinner",
      "servings" : 2,
      "dietary" : "vegan",
      "notes" : ""
      },
      
]);

db.planner.insertMany([
  {
    "name" : "Balmoral Chicken",
    "ingredients" : [
        { "amount" : 4,
        "ingredient" : "chicken breasts" },
        { "amount" : 130,
        "unit" : "g",
        "ingredient" : "haggis" },
        { "amount" : 4,
        "ingredient" : "rashes of bacon" },
        { "amount" : 30,
        "unit" : "ml",
        "ingredient" : "olive oil" },
        { "amount" : 20,
        "unit" : "g",
        "ingredient" : "butter" },
    ],
    "method" : "1. Preheat oven to 180°C. \n 2. Slice down the side of each chicken breast, making a pocket. \n 3. Slice the haggis into small chunks and squidge (technical term) into the chicken pocket. \n 4. Wrap each breast in a rasher of bacon and secure with a toothpick if necessary. \n 5. Heat the oil and butter in a non-stick frying pan, sear the bacon wrapped around the chicken breasts. Give 2 minutes on each side. \n 6. Place in an oven proof dish and transfer to the oven for 35-40 minutes or until cooked through & piping hot. \n 7. Serve with the peppercorn sauce and a selection of vegetables and/ or mash potato.",
    "image": "https://www.carolinescooking.com/wp-content/uploads/2022/01/haggis-stuffed-chicken-Balmoral-featured-pic-sq.jpg"
}
])